### PR TITLE
Release/v3.1.0 - sync with develop

### PR DESCRIPTION
**Pull request by rossneilson**

### CODE REVIEW

**Comment by dcrescimbeni** [comment]
I'm getting `SUPPORTED_DAVI_NETWORKS` missing:
image

and can't run this build.

Is it happening for everyone else?

**Comment by rulfo71** [comment]
i'm getting the same as @dcrescimbeni:

image

on #251 we changed the name of `SUPPORTED_DAVI_NETWORKS` to `CHAIN_ID`:

image

**Comment by rossneilson** [comment]
> We have to Find all `SUPPORTED_DAVI_NETWORKS` and replace them with `CHAIN_ID`:
> 
> i'm getting the same as @dcrescimbeni:
> 
> image
> 
> on #251 we renamed `SUPPORTED_DAVI_NETWORKS` to `CHAIN_ID`:
> 
> image

Ah got it, thanks. Was confused and thought the develop version was the new one. Fixed build issues

**Review by dcrescimbeni — APPROVED** [review]
Working great now!

**Pull request merged**
