### PR TITLE
v2.0 support

### PR DESCRIPTION
**Pull request by MiltonTulli**
### Summary: 
- Update `dxdao-contracts` branch to `v2.0`
- Create script to update abis after compile
- Remove unnecessary abis and fix/rename others
- Update abis with new v2 artifacts
- Create a /packages folder with
    - graph-node (docker stuff)
    - dev-scripts
    - dxdao-contracts
 - Use /davi/.env file with graphClient endpoints (both subgraphs) to build graph-client to point to local subgraphs
    Please add to your current config: (included in env.example)
    ```
    DXGOV_GUILD_GRAPHQL_ENDPOINT=http://127.0.0.1:8000/subgraphs/name/dxdao/guilds
    DXGOV_DAO_GRAPHQL_ENDPOINT=http://127.0.0.1:8000/subgraphs/name/dxdao/dao
    ```
- Remove `dev` script for now and force the developer to run 4 processes documented in the readme file (devScript, start docker, deploy subgraphs, start davi). 
- Rename "1-5-subgraph" for "dao-subgraph". It was throwing a type error because of the automatic graph client build.

### Considerations
- This pr should be ready to start using on development. 
-  Build/deploy won't work for now. Since davi needs both deployed subgraphs endpoints (deployed/productive subgraphs) to build graph-client it will break since the existing abis/config after this pr doesn't match (more or less) with deployed subgraph (https://api.thegraph.com/subgraphs/name/dxgovernance/guild-subgraph-gnosis) types. We need to deploy both guilds and 1.5 subgraphs with support to v2 branch as included on this pr first, to be able to build/deploy davi. I think we should do this with some versioning support to avoid breaking the previous build until this is pr/branch is ready to deploy and also we have the flexibility to point to any subgraph URL at build time. 

### How to test this: 
- Checkout to this branch: `gh pr checkout https://github.com/DXgovernance/davi-monorepo/pull/200`
- Remove old dxdao-contracts  and dev-scripts from apps if still present: `rm -rf apps/dxdao-contracts apps/dev-scripts`
- Since this pr moves dxdao-contracts to /packages you might need to clone it again: `cd packages/dxdao-contracts && git clone -b v2.0 https://github.com/DXgovernance/dxdao-contracts`
- Update davi .env file with new keys.
- `pnpm install`
- Follow the development instructions of readme file

### CODE REVIEW

**Comment by dcrescimbeni** [comment]
The error for the mismatching properties was because in the `.graphclientrc.yml` file, we were pointing to the deployed graph instead of the local one, then the URL we use for the actual queries (`clients/apollo.ts`) has the localhost route.

**Comment by dcrescimbeni** [comment]
Works well!

Had some problems running the setup on Linux, but that's more of a quirk of the way the `setup-linux.sh` works. After that's configured, everything runs smoothly.

**Comment by dcrescimbeni** [comment]
Some comments for someone trying this PR:

1. Had to delete `apps/dev-scripts` and `apps/1-5-subgraph` manually 
2. Had to do a checkout to the v2 branch of the dxdao-contracts because it was pointing to a commit that didn't have the `getProposalTimes` method

After that, running every command worked great :ok_hand:

**Comment by rulfo71** [comment]
should we test this or wait until it's not WIP ?

**Comment by rulfo71** [comment]
working for me too on Mac! 
I did what dino mentions, and also removing `dxdao-contracts` from `/apps` and cloning it from `/packages`

also i had to run `pnpm run subgraph:dev` with `--force`

**Comment by MiltonTulli** [comment]
> working for me too on Mac!
> 
> I had to follow the new readme, did what dino mentions, and also removing `dxdao-contracts` from `/apps` and cloning it from `/packages`
> 
> also i had to run `pnpm run subgraph:dev` with `--force`

Thanks for testing! I updated this pr description with the steps. Also removed the cache build for subgraphs so there is no need to `--force` subgraphs:dev

**Comment by dcrescimbeni** [comment]
Guilds in Gnosis seem to be broken. This is what I see:

image

Guilds on localhost work OK :+1:

**Review by dcrescimbeni — APPROVED** [review]

**Review by dcrescimbeni — DISMISSED** [review]
Everything works great.

The previous issue where the guild data wasn't loading is fixed too.

**Review by rulfo71 — APPROVED** [review]

**Comment by rulfo71** [comment]
Working perfect for me, i was able to run davi, create a proposal and vote for it with everything working smoothly. 

for anyone testing it, remember as the readme says to change `./apps/guilds-subgraph/src/mappings/Create2Deployer/mapping.ts#L13` (const deployedHashedBytecodesJSON = local)

great work!

**Pull request merged**
