### PR TITLE
feat: handle verification of wallet connectivity

### PR DESCRIPTION
**Pull request by yathindrak**
Before each transaction is processed, the wallet connectivity will be checked with this PR and the wallet selector will be prompted. Additionally before clicking on the action buttons related to creating a discussion has also checked.

Closes: https://github.com/DXgovernance/davi-monorepo/issues/125

### CODE REVIEW

**Comment by dcrescimbeni** [comment]
Closing the wallet modal will continue the navigation to the discussion creation page.

I think the logic for opening the wallet modal should be handled in the CreateDiscussion page, not in every main page.

Maybe render a button to toggle the modal if there is not wallet connection?

**Comment by mprasanjith** [comment]
> Closing the wallet modal will continue the navigation to the discussion creation page.
> 
> I think the logic for opening the wallet modal should be handled in the CreateDiscussion / CreateProposal page, not in every main page.
> 
> Maybe render a button to toggle the modal if there is not wallet connection?

@dcrescimbeni Actually this is the expected behavior. Yathindra and I was talking to Ross about this. We still want to let people be able to access these pages without completely blocking them. They will get re-prompted to connect their wallet when trying to interact with the contracts anyway.

**Comment by rulfo71** [comment]
hey! i think we're missing the connectTheWalletToProceed on translation.json

image

**Comment by yathindrak** [comment]
> hey! i think we're missing the connectTheWalletToProceed on translation.json
> 
> image

@rulfo71 Thanks for pointing that out. Seems to be missed when conflicts resolving. This is fixed with https://github.com/DXgovernance/davi-monorepo/pull/187/files#diff-20d72d7855ef9bf4887781f65f9fe75835ea971ef5b8477434c61140198e2467R35. Can you check now?

**Review by rossneilson — APPROVED** [review]

**Pull request merged**
