### PR TITLE
Create Proposal mint rep test

### LINKED ISSUE #276: Automation - e2e test: Create MintREP Proposal
Automation of `MintREP` Proposal creation

### PR DESCRIPTION
**Pull request by Filipv95**
# Description
- Added flow for creation of MintREP Proposal 
- Updated README file

Closes #276 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
ATM instructions from readme won't work so here is work-around

1. run `localhost` separately (using 4 terminals described in README)
2. go to `apps/davi` > `package.json` there you will find `runRegressionLocal` command
3. at the end of the `runRegressionLocal` command instead of astrix (*) put name of the test you want to run in this case `CreateMintRepProposal.spec.ts`
4. run `pnpm runRegressionLocal` in new terminal

That should run the test pointing to `localhost` URL 

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by rulfo71** [comment]
hey @Filipv95, finally got to run this 😅. 
i haven't seen cypress running before, it's awesome, great work! 

the testing worked fine but couldn't finish the run because it's actually failing on davi when minting rep. i tried it manually and i'm getting an error when clicking on `Save Action` on the mint rep action: 
image

I think we had a fix for this so maybe you just have to merge develop to this branch.

**Comment by Filipv95** [comment]
@rulfo71 Hey 

> hey @Filipv95, finally got to run this 😅. i haven't seen cypress running before, it's awesome, great work!
> 
> the testing worked fine but couldn't finish the run because it's actually failing on davi when minting rep. i tried it manually and i'm getting an error when clicking on `Save Action` on the mint rep action: image
> 
> I think we had a fix for this so maybe you just have to merge develop to this branch.

Hey, @rulfo71 the issue could be that I try to create proposal on Carrot Guild instead of Localhost, since I get transaction rejected. I can't create manually proposal on Carrot guild also.

Can we merge this now and I will fix that in another PR?

**Comment by rulfo71** [comment]
Hey @Filipv95 ! i'm not sure i understand, why are you creating it in carrot guild instead of localhost? 
Sorry i missed to answer this today, maybe we can make a call on monday

**Review by rulfo71 — APPROVED** [review]
Approving it as @Filipv95 is fixing the problems that are making the test fail on another pr

**Pull request merged**
