### PR TITLE
feat: Proposal Rendering Fixes

### LINKED ISSUE #7: Handle null ENS avatar
With pulen.eth for example returns an avatar URL which does not resolve so we should fallback in this case to the default icon

### PR DESCRIPTION
**Pull request by mprasanjith**
- Updates `ProposalDescription` to render both HTML and markdown content correctly.
- Updates Proposal and Discussion pages to both create Markdown for proposal descriptions.
- Fix ENS avatars when loading from ENS Metadata Service.
- Show ENS avatars in proposal cards.

This intentionally uses `is-html` v2.0.0 as the latest v3.0.0 is pure ESM, which our jest test suite doesn't seem to like. There are no other changes in v3.

Fixes #7.

### CODE REVIEW

**Comment by mprasanjith** [comment]
@rossneilson Should we switch back to using Markdown in proposal editor? It might be better for compatibility reasons with other governance frameworks, for example...

**Comment by rossneilson** [comment]
Seems markdown isnt rendered quite perfectly
https://davi-git-fork-mprasanjith-feature-proposal-renderi-44fe06-dxgov.vercel.app/#/gnosis/0x3f842726188FcD932d43bcA291be28138228e6D9/discussion/kjzl6cwe1jw14aob92db6wqxth9xqmahgwdleajir838aucb5nfmqw05i13to6n
Screenshot 2023-02-09 at 09 53 17

**Comment by dcrescimbeni** [comment]
Having the same problem with markdown render in Yathindra's discussion.

The rest of the code looks OK

**Comment by mprasanjith** [comment]
@dcrescimbeni I think Yathindra's posts have invalid markdown formatting in the first place. @yathindrak said he wanted to edit and fix it but we don't have a way to edit things yet so couldn't.

**Comment by dcrescimbeni** [comment]
Linking null ENS avatar issue: #7

**Review by rossneilson — APPROVED** [review]
Ah yeah makes sense, lets resolve any oddities with our markdown formatting in a later issue

**Review by rossneilson — APPROVED** [review]

**Pull request merged**
